config/routes.rb
Rails.application.routes.draw do

  root 'main#index'
  get 'about' => 'main#about'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy' #link

  resources :posts, only: [:create,:new,:index]

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password#this exposes a field in the model....it will encrypted

  validates :email,#what you want to validate
  presence:true, #that they're entering an email
  uniqueness: {case_senesitive:false}

  validates_presence_of :password, on: :create #will validate there's a password present

  has_many :posts

  def self.authenticate email,password
    User.find_by_email(email).try(:authenticate, password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def is_authenticated?
    unless @current_user
      flash[:danger] = 'ACCESS DENIED!!!!'
      redirect_to login_path
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  before_action :is_authenticated?, except: [:index]

  def index
  end

  def about

  end

  def secret
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :is_authenticated?

  def index
    @posts = @current_user.posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @current_user.posts.create posts_params
    redirect_to posts_path
  end

  private
    def posts_params
      params.require(:post).permit(:title,:link)
    end
end

app/controllers/sessions_controller.rb
  class SessionsController < ApplicationController

  def new
    # render plain: "new session"
  end

    #login action (create a session)
  def create
    # render json: params #testing line to make sure data is going through
    # render plain: "create session"
    user = User.authenticate(params[:user][:email],
     params[:user][:password])#from json data params is the curly brace user, email and password are the keys in the json file
      if user
        #correct email / password
        session[:user_id] = user.id
        flash[:success] = 'You are now logged in.'#:success can be any value
        redirect_to root_path
      else
        #wrong email or password
        flash[:danger] = 'Invalid email or password'
        #render :new
        redirect_to login_path
      end
  end

  #logout action (invalidates thw session)
  def destroy
    # render plain: "destroy session"
    session[:user_id] = nil
    flash[:info] = "You are logged out."
    redirect_to login_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hacker News App</title>
  <!-- Latest compiled and minified CSS & JS -->
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 col-offset-2">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Th&#477; H@ck&#477;rs N&#477;ws</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Posts", posts_path %></li>
              <li><%= link_to "About", about_path %></li>
                <% if @current_user %>
              <li><%= link_to "Create Post", new_post_path %></li>
                  <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if @current_user %>
              <li>Hello <%= @current_user[:name] %></li>
              <li><%= link_to "logout", logout_path %></li>
                <% else %>
              <li><%= link_to "login", login_path %></li>
                <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 col-offset-2">
      <div class="well">
        <p>HN Search provides real-time full-text search for the HackerNews community site. Source code is available on GitHub. The search backend is implemented using Algolia instant search engine.</p>
      </div>
      <%= yield %>
    </div>


  </div>
</div>

</body>
</html>

app/views/main/about.html.erb
<h1>Main#about</h1>
<p>Find me in app/views/main/about.html.erb</p>

app/views/main/index.html.erb
<%= render "shared/flash" %>

<!-- <div class="col-xs-4 col-sm-6 col-md-8 col-lg-12"> -->

app/views/main/secret.html.erb
<h1>Main#secret</h1>
<p>Find me in app/views/main/secret.html.erb</p>

app/views/posts/index.html.erb
<h1>My Posts</h1>
<ul>
  <% @posts.each do |post| %>
    <li><%= post.title %> - <a href="<%= post.link %>"><%= post.link %></a></li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<%= bootstrap_form_for @post do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :link %>
  <%= f.primary %>
<% end %>

app/views/posts/show.html.erb
<h1>Popular Posts</h1>


<%= link_to "&larr; back".html_safe, post_path, :class=>"btn btn-primary btn-xs back" %>
<%= link_to "", new_post_path, class: 'btn btn-primary btn-xs glyphicon glyphicon-plus pull-right' %>

  <div class="well">
    <p><span class = "creatures">
      Title: <%= @post.title %></span> |
      Posted At:  <%= @post.created_at%>
    </p>
    <p>link: <%= @post.link %></p>


  </div>

app/views/shared/_flash.html.erb
<% flash.each do |k,v| %>
  <div class="alert alert-<%= k %>">
    <%= v %>
  </div>
<% end %>